apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eureka
  template:
    metadata:
      labels:
        component: eureka
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_URI
        - name: SPRING_EUREKA
          value: http://eureka:8761/eureka
        image: dhananjay12/eureka-server:latest
        name: eureka
        ports:
        - containerPort: 8761
